Enable caching for faster builds
RobotLocomotion/pip-drake pull request #13
Opened 2021-09-07 15:53 UTC by jwnimmer-tri

Specifically:

- Cache the files downloaded via apt across Docker invocations, so that we don't pound the network when our apt dependencies change a little.
- Cache the bazel build results across Docker invocations, so that rebuilds are fast while testing small changes.

Eventually we may want a "gold build" flag that opts-out of caching for when we're actually doing real releases, or to make the caching opt-in, but during active development it seems like "fast by default" is better.

2021-09-07 16:51 UTC, mwoehlke-kitware requested changes
Please split the Bazel version and URI changes into a separate PR; those look non-controversial.

The caching is... concerning. Specifically, it requires BuildKit, which is not available on stock Docker (at least as of Bionic), nor on Podman. That is going to seriously limit the environments in which this stuff can be used. (In particular, I might not be able to build images *at all*.) It would be safer if there was a way to make this optional.

2021-09-07 16:51 UTC, mwoehlke-kitware commented on Dockerfile
> +  /image/provision.sh
Um... okay, I guess (but see general notes). The provisioning script doesn't change that much, though, so rebuilding the base image should be fairly uncommon. Given that you mentioned we may *not* want caching for "gold" releases, I wonder if this is worthwhile?

2021-09-07 16:51 UTC, mwoehlke-kitware commented on Dockerfile
> +RUN --mount=target=/var/cache/bazel,type=cache /image/build-drake.sh
```suggestion
RUN \
  --mount=target=/var/cache/bazel,type=cache \
  /image/build-drake.sh
```

2021-09-07 16:53 UTC, jwnimmer-tri commented
I'm using Docker on Bionic via APT.  I _thought_ it was the stock Docker.  I'll go back and check.

2021-09-07 19:38 UTC, jwnimmer-tri commented
> Please split the Bazel version and URI changes into a separate PR; those look non-controversial.

Done.

> The caching is... concerning. Specifically, it requires BuildKit, which is not available on stock Docker (at least as of Bionic), ...

It works fine for me on stock Bionic, using `sudo apt install docker.io= 20.10.7-0ubuntu1~18.04.1`.

> That is going to seriously limit the environments in which this stuff can be used. (In particular, I might not be able to build images at all.) It would be safer if there was a way to make this optional.

Sounds fine, I will rework this to have some kind of toggle.

However, I think that as we work to get Drake's workspace-related patches merged, using cached builds of Drake is going to be table stakes, at least for me.  Waiting 10-20 minutes to test each one-line change seems like a a non-starter, when it could be just a few tens of seconds.  I recommend that you find a way to use caching, so that you can more effectively help iterate on Drake patching, whether though this PR, or some alternative change you might have in mind.  From my internet searching, this current patch _seems_ like the best practice to share cache folders across Docker builds.

2021-09-07 19:58 UTC, mwoehlke-kitware commented
> However, I think that as we work to get Drake's workspace-related patches merged, using cached builds of Drake is going to be table stakes, at least for me.

Sure, it's definitely a pain ATM. Also, I'm much more interested in getting Bazel's cache working (bonus if it can work for podman, also; is there a way to leverage `VOLUME` for this?).

Given that *installing* packages from `apt`, not to mention `pip`, and *building* dependencies (VTK in particular) takes a significant amount of time, I'm less confident that mucking about with `apt` cache is a useful win. That stuff should not change often, and the *download* step shouldn't be taking all that long unless your connection is really slow. Realistically, the price you're going to pay for rebuilding VTK if the "base" layer changes is going to comfortably exceed the price for not having an apt cache.

If we're really *that* concerned about hitting the network more than absolutely necessary on those hopefully-rare occasions that the "incubator" layer changes, we probably should also be caching the pip and drake-dependencies downloads. (At least the latter; I'm not sure if pip downloads *can* be cached. We might need to tweak drake-dependencies, but *that* should be possible to cache; it's a simplified version of [fletch](https://github.com/Kitware/fletch/), which as I understand is used by folks with *no* network.)

Also, if we're really, really concerned about the time it takes to rebuild the lower layers, maybe we should use ccache?

2021-09-07 20:06 UTC, mwoehlke-kitware commented
That all said, I also don't advise using `docker build` to test change to Drake itself. Use `docker run` with the image used to run `build-drake.sh` and test changes within the running container. That'll be even faster.

2021-09-13 16:44 UTC, jwnimmer-tri commented
>  That stuff should not change often, and the download step shouldn't be taking all that long unless your connection is really slow.

I've withdrawn that part of the change (the apt caching).

> > That is going to seriously limit the environments in which this stuff can be used. (In particular, I might not be able to build images at all.) It would be safer if there was a way to make this optional.
>
> Sounds fine, I will rework this to have some kind of toggle.

FYI I just rebased this PR, but have not yet implemented that toggle.  I'll still need to do that before we can merge this.

2021-09-28 21:57 UTC, mwoehlke-kitware commented
Circling back to this after some recent CI woes... it seems our CI uses remote caching? Maybe something like that could be useful here to avoid needing to know Dockerkit magic? (Actually, I am surprised now we aren't using a shared cache? Or does Bazel not support that?)

2021-09-28 23:29 UTC, jwnimmer-tri commented
Bazel can cache build and test results using either a local filesystem cache, or a web cache at some URL.  If desired, one can use the cache for reading, but not write back to it.

Drake CI uses the web cache (not a local filesystem cache), so that the dozens+ of concurrent builds can all share their already-completed build results with each other.  For any given ephemeral build machine, the build variant (Debug, Release, CXX=clang-9, etc.) varies a lot from one build to the next, so a filesystem-local cache would not see very many cache hits.  The web cache lets us share across machines much more effectively.

For the Drake CI builds that publish official images, we do not have any caching enabled, so that we can be sure that any kind of cache pollution cannot contaminate our releases.

It would not make sense to try to have pip-drake builds check the Drake CI cache for hits, at least not as of today.  For pip, we're using a different version of Eigen and almost everything else, so I would expect practically zero overlap with CI's existing actions.  Possibly once we have nightly builds of pip-drake running in Drake CI, we could have a way to opt-in to that read-only cache to accelerate local users.

Once we make a plan for how to get this code under CI, we can see if it makes sense for it to access the CI cache.

In this PR, I was proposing using the disk cache, since the build is necessarily happening on just the one, local machine.  Running a local-only http server during the build (with a writeable webdav, or similar) just to pretend to be a local filesystem, would be lot of extra complexity.

All 50+ Drake developers (even beyond just TRI) have access to Ubuntu locally, which has BuildKit built-in already, without any extra hassle, so this PR (once I revise it) will able to help them.  I do still plan to rework this PR to offer a toggle for BuildKit so that it won't break your workflow, but I don't think it's worth playing with web-based caching, since almost everyone will have access to this local caching mechanism.

If you figure out a way to offer a persistent temp filesystem into your variant of docker, we can merge that into pip-drake under a toggle, in addition to this mechanism.

2021-10-25 21:26 UTC, jwnimmer-tri commented
As of https://github.com/RobotLocomotion/drake/pull/15977 this code lives in Drake now.  I'll eventually re-submit this change as a Drake PR.

2021-10-25 21:26 UTC, closed without merging